# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from documents.v1 import document_service_pb2 as documents_dot_v1_dot_document__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in documents/v1/document_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractDraft = channel.unary_unary(
                '/documents.v1.DocumentService/ExtractDraft',
                request_serializer=documents_dot_v1_dot_document__service__pb2.ExtractDraftRequest.SerializeToString,
                response_deserializer=documents_dot_v1_dot_document__service__pb2.ExtractDraftResponse.FromString,
                _registered_method=True)
        self.CompleteDraft = channel.unary_unary(
                '/documents.v1.DocumentService/CompleteDraft',
                request_serializer=documents_dot_v1_dot_document__service__pb2.CompleteDraftRequest.SerializeToString,
                response_deserializer=documents_dot_v1_dot_document__service__pb2.CompleteDraftResponse.FromString,
                _registered_method=True)
        self.CreateDocument = channel.unary_unary(
                '/documents.v1.DocumentService/CreateDocument',
                request_serializer=documents_dot_v1_dot_document__service__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=documents_dot_v1_dot_document__service__pb2.CreateDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/documents.v1.DocumentService/GetDocument',
                request_serializer=documents_dot_v1_dot_document__service__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=documents_dot_v1_dot_document__service__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/documents.v1.DocumentService/ListDocuments',
                request_serializer=documents_dot_v1_dot_document__service__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=documents_dot_v1_dot_document__service__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.ResetDocuments = channel.unary_unary(
                '/documents.v1.DocumentService/ResetDocuments',
                request_serializer=documents_dot_v1_dot_document__service__pb2.ResetDocumentsRequest.SerializeToString,
                response_deserializer=documents_dot_v1_dot_document__service__pb2.ResetDocumentsResponse.FromString,
                _registered_method=True)
        self.GetDownloadDescriptor = channel.unary_unary(
                '/documents.v1.DocumentService/GetDownloadDescriptor',
                request_serializer=documents_dot_v1_dot_document__service__pb2.GetDownloadDescriptorRequest.SerializeToString,
                response_deserializer=documents_dot_v1_dot_document__service__pb2.GetDownloadDescriptorResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadDescriptor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractDraft,
                    request_deserializer=documents_dot_v1_dot_document__service__pb2.ExtractDraftRequest.FromString,
                    response_serializer=documents_dot_v1_dot_document__service__pb2.ExtractDraftResponse.SerializeToString,
            ),
            'CompleteDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteDraft,
                    request_deserializer=documents_dot_v1_dot_document__service__pb2.CompleteDraftRequest.FromString,
                    response_serializer=documents_dot_v1_dot_document__service__pb2.CompleteDraftResponse.SerializeToString,
            ),
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=documents_dot_v1_dot_document__service__pb2.CreateDocumentRequest.FromString,
                    response_serializer=documents_dot_v1_dot_document__service__pb2.CreateDocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=documents_dot_v1_dot_document__service__pb2.GetDocumentRequest.FromString,
                    response_serializer=documents_dot_v1_dot_document__service__pb2.GetDocumentResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=documents_dot_v1_dot_document__service__pb2.ListDocumentsRequest.FromString,
                    response_serializer=documents_dot_v1_dot_document__service__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'ResetDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDocuments,
                    request_deserializer=documents_dot_v1_dot_document__service__pb2.ResetDocumentsRequest.FromString,
                    response_serializer=documents_dot_v1_dot_document__service__pb2.ResetDocumentsResponse.SerializeToString,
            ),
            'GetDownloadDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadDescriptor,
                    request_deserializer=documents_dot_v1_dot_document__service__pb2.GetDownloadDescriptorRequest.FromString,
                    response_serializer=documents_dot_v1_dot_document__service__pb2.GetDownloadDescriptorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'documents.v1.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('documents.v1.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documents.v1.DocumentService/ExtractDraft',
            documents_dot_v1_dot_document__service__pb2.ExtractDraftRequest.SerializeToString,
            documents_dot_v1_dot_document__service__pb2.ExtractDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documents.v1.DocumentService/CompleteDraft',
            documents_dot_v1_dot_document__service__pb2.CompleteDraftRequest.SerializeToString,
            documents_dot_v1_dot_document__service__pb2.CompleteDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documents.v1.DocumentService/CreateDocument',
            documents_dot_v1_dot_document__service__pb2.CreateDocumentRequest.SerializeToString,
            documents_dot_v1_dot_document__service__pb2.CreateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documents.v1.DocumentService/GetDocument',
            documents_dot_v1_dot_document__service__pb2.GetDocumentRequest.SerializeToString,
            documents_dot_v1_dot_document__service__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documents.v1.DocumentService/ListDocuments',
            documents_dot_v1_dot_document__service__pb2.ListDocumentsRequest.SerializeToString,
            documents_dot_v1_dot_document__service__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documents.v1.DocumentService/ResetDocuments',
            documents_dot_v1_dot_document__service__pb2.ResetDocumentsRequest.SerializeToString,
            documents_dot_v1_dot_document__service__pb2.ResetDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDownloadDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documents.v1.DocumentService/GetDownloadDescriptor',
            documents_dot_v1_dot_document__service__pb2.GetDownloadDescriptorRequest.SerializeToString,
            documents_dot_v1_dot_document__service__pb2.GetDownloadDescriptorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
